empresa: SAN JOSE
title: SAN JOSE | Higiene, Seguridad &amp; Medio Ambiente
description: Consultor√≠a de Seguridad e Higiene, Planes de evacuacion y Seguridad en la construccion
phone: "1144221404"
email: info@sanjoseconsultora.com
facebook: https://www.facebook.com/sanjoseconsultora
address: Tierra del Fuego

css:
  bootstrap: https://stackpath.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
  font-awesome: https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
  font: https://fonts.googleapis.com/css13b7.css?family=Open+Sans:400,300,600,700
js:
  bootstrap: https://stackpath.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
  jquery: https://code.jquery.com/jquery-1.11.1.min.js
